version: 0.2

env:
  variables:
    IMAGE_TAG: latest
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - IMAGE_REPO_URI=$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $IMAGE_REPO_URI
  build:
    commands:
      - echo Build started on `date`
      - docker build -t $IMAGE_REPO_URI:$IMAGE_TAG .
  post_build:
    commands:
      - docker push $IMAGE_REPO_URI:$IMAGE_TAG
      - printf '{"ImageUri":"%s"}' $IMAGE_REPO_URI:$IMAGE_TAG > imageDetail.json
artifacts:
  files:
    - imageDetail.json
